### ISSUE TITLE
Im Getting This Error (Termux) 

### ISSUE THREAD

**Issue by buraca27** [vivinano/MudaeAutoBot#120]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/MudaeAutoBot/MudaeAutoBot.py", line 31, in <module>
    settings = json.load(jsonf)
  File "/data/data/com.termux/files/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/data/data/com.termux/files/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/data/data/com.termux/files/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/data/com.termux/files/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 26 column 4 (char 553)

**Comment by vivinano** [comment]
Json file formatting is broken it seems like your missing a ,
