### ISSUE TITLE
KeyError: 'user'

### ISSUE THREAD

**Issue by Aries298** [vivinano/MudaeAutoBot#137]
I'm trying to pinpoint the issue and thought I might ask about it here. The bot runs on Replit without any issues but it suddenly stopped working. After restarting it gives the following error:
![errrore](https://user-images.githubusercontent.com/85286463/153757213-8023088a-a268-4951-aa16-d42902354c0a.PNG)

**Comment by vivinano** [comment]
Seems your discord token might have changed so check that

**Comment by ChocoTonic** [comment]
no I believe it's an issue with discum because I just got the error as well. let me know if it is still working on your end

**Comment by vivinano** [comment]
It could be an issue with discum.

It currently is working for me personally When I ran it when the issue first arose. 

If it was installed thru pypi then it's an older version of discum

Which should be installed thru their GitHub repo

**Comment by ChocoTonic** [comment]
could I know what version of discum you're using?

what specifically is working for you? discum or mudaeautobot?

discum is personally still working for me on other scripts still but it's specifically this line
user = bot.gateway.session.user
and anything related to gateway.session that is giving that keyerror

this is the output that I'm getting 

![image](https://user-images.githubusercontent.com/41702116/154172395-a67b0990-e9ac-4b6d-83f0-f5d735d3c739.png)

**Comment by vivinano** [comment]
I'm currently on discum 1.3.1

**Comment by Epikest** [comment]
> 

i'm getting the same issue, have tried 1.3.1 from github releases, 1.4.0 from github releases, and latest from pypi

**Comment by ChocoTonic** [comment]
> i'm getting the same issue, have tried 1.3.1 from github releases, 1.4.0 from github releases, and latest from pypi

is it failing on 1.3.1 also for you?

**Comment by Epikest** [comment]
> 

yep

**Comment by vivinano** [comment]
okay viewing the discum repo there has been a captcha added that i think is messing with the key error. 
I've emailed the dev over there and am awaiting for a reply

**Comment by Epikest** [comment]
thanks

**Comment by Epikest** [comment]
if discum doesn't work, you can use [discord.py-self](https://github.com/dolfies/discord.py-self), it's well maintained

**Comment by ChocoTonic** [comment]
moving there would have a lot of overhead, but yeah that's an option

**Comment by vivinano** [comment]
yeah I originally was on discord.py before the self bot portion of code was deprecated and I personally wouldn't like to overhaul the code again. Also in terms of development the same guy who works on discum works on discord.py-self so I'm sure he is figuring out a fix

**Comment by vivinano** [comment]
still awaiting a reply but haven't received anything on my end. anyone else got a solution ?

**Comment by vivinano** [comment]
https://github.com/Merubokkusu/Discord-S.C.U.M/issues/334

**Comment by Epikest** [comment]
anything yet?

**Comment by vivinano** [comment]
No the dev over there has been busy. But did report a few solutions over on his repo

**Comment by ChocoTonic** [comment]
there isn't a way to just remove the broken section?

**Comment by vivinano** [comment]
The user is to verify that user has successfully logged in and that user has been set

**Comment by MujurID** [comment]
i think in "#take care of channels" in /discum/gateway/start/parse.py , because if i disable i can get ready_data or ready_data["user"]

![image](https://user-images.githubusercontent.com/40834757/164170857-6b3aa553-15f4-44bc-826a-188564c19b67.png)

**Comment by ChocoTonic** [comment]
Can you be more specific about what you changed or did differently?

**Comment by Idiot1183** [comment]
How was this fixed?

**Comment by aspectlostx** [comment]
> How was this fixed?

Think they were just referencing you to this page instead of having two open. Not fixed yet

**Comment by aspectlostx** [comment]
After trying to fix it, i see it can work perfectly fine on alt accounts but not my main account. I have reset my token by changing my password, doing a lot of things. No luck.. Maybe discord has some sort of shadowbans?? I'm not sure why my main account no longer works with this bot. @MujurID maybe its something to do with servers?? do you think that for this bot?

**Comment by Idiot1183** [comment]
> After trying to fix it, i see it can work perfectly fine on alt accounts but not my main account. I have reset my token by changing my password, doing a lot of things. No luck.. Maybe discord has some sort of shadowbans?? I'm not sure why my main account no longer works with this bot. @MujurID maybe its something to do with servers?? do you think that for this bot?

But that can't be. The same user token works on another discum program that I made. `bot.gateway.session.user` is the problem.

**Comment by aspectlostx** [comment]
Confirmed I just fixed it by getting rid of mostly all my servers I don't need anymore. @MujurID 's solution does work (for me). I do not know what specific thing causes it but yeah!

**Comment by Idiot1183** [comment]
> @vivinano - Confirmed I just fixed it by getting rid of mostly all my servers I don't need anymore. I do not know what server specifically made it work and I know this makes zero sense as the problem is based on the user and discum but @MujurID 's solution does work (for me). Might have to do with a certain string as they mention certain servers/channels may have characters that conflict? No clue.

Holy, you're right. leaving does work. For anyone wondering what I left it was my universities hub or hub server or discord student hub or whatever you want to call it

**Comment by ChocoTonic** [comment]
did the servers you left contain >1000+ members? @Idiot1183 @aspectlostx

**Comment by aspectlostx** [comment]
> did the servers you left contain >1000+ members? @Idiot1183 @aspectlostx

I left many servers less than and more than 1000 members definitely. Most of the servers I left were 1000+ however

**Comment by Idiot1183** [comment]
> did the servers you left contain >1000+ members? @Idiot1183 @aspectlostx

I have no idea why what was messing mine up was the student hub.  But I’m still in a server with nearly 100k people so I genuinely have no idea

**Comment by aspectlostx** [comment]
> did the servers you left contain >1000+ members? @Idiot1183 @aspectlostx

I know mine I left discord.js, community servers like games, bots like dank memer's and useless things I really didn't need anymore. It's not like I joined something new too. Genuinely some server probably made a channel or changed a name and it did something?? I dont know haha

**Comment by Darnerguy** [comment]
Same solution worked for me, I just left as many servers as possible (including my student hub). After making sure the bot could run without errors, I created a test server with `'` and `"` in the channel descriptions, but the bot still worked fine, so I'm not sure where exactly the problem lies.

**Comment by vivinano** [comment]
https://discordhelp.net/discord-token

according to @HentaiRyuu new method to get token is needed

**Comment by ChocoTonic** [comment]
@vivinano how is this different than getting the token from library? are tokens treated differently based on where you get them?

**Comment by HentaiRyuu** [comment]
@ChocoTonic It is same, old token (in `Local Storage`) can be use same as usual.
only new generate token will be obfuscate. thats why this method is needed

**Comment by ChocoTonic** [comment]
so what does this have to do with the mudaeautobot?
if I already have a token, and I'm assuming that generating a new token will not fix this issue otherwise someone would have already reported that that's a reliable fix, then what is the point of the above post?

**Comment by vivinano** [comment]
> so what does this have to do with the mudaeautobot? if I already have a token, and I'm assuming that generating a new token will not fix this issue otherwise someone would have already reported that that's a reliable fix, then what is the point of the above post?

according you Ryuu he was gettiing a 4004 error code from the gateway so which to discord is a authentication payload error

![image](https://user-images.githubusercontent.com/33008397/168622287-7383daf6-d18d-42c8-96ba-15d100ed0f31.png)

but still just spitballing and seeing where the possible error is

**Comment by kleborgn** [comment]
Leaving all the hubs I was in fixed the error for me

**Comment by ChocoTonic** [comment]
how can I identify which servers I'm in are hubs? @kleborgn

**Comment by kleborgn** [comment]
> how can I identify which servers I'm in are hubs? @kleborgn

The icon is blue with a student hat. If you right-click on it, it says "Leave the hub" instead of "Leave the server".

![image](https://user-images.githubusercontent.com/3341364/168988806-ce3b9ee3-752e-4907-94cb-d6d582b8f3fa.png)

**Comment by ChocoTonic** [comment]
I see. I don't have any hubs, but I am in large servers and it does not work for me

**Comment by aspectlostx** [comment]
> I see. I don't have any hubs, but I am in large servers and it does not work for me

Check on a new alt account. I still am running the bot on two accounts with no issues since the fix I said worked. Just try leaving servers you do not need anymore. Hubs aren't the only cause

**Comment by ScikuVRC** [comment]
`Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x000002B223FA3CD0>>
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Python\Python310\site-packages\discum\gateway\gateway.py", line 299, in _response_loop
    func(resp)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\MudaeAutoBot-4\MudaeAutoBot.py", line 694, in on_message
    c_settings = parse_settings_message(msg)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\MudaeAutoBot-4\MudaeAutoBot.py", line 223, in parse_settings_message
    settings['prefix'] = val_parse(settings_p[0])[0]
IndexError: list index out of range`

Tried all the fixes above, even tried the thing @MujurID suggested, nothing seems to make the bot function.

**Comment by BellaDona007** [comment]
I had solved this problem by leaving some servers, but now it's back and I have no idea what happened or who I should look for to get this error out =\

**Comment by ScikuVRC** [comment]
Normal Syntax doesn't work but, installing latest Discum + copying all Mudae $settings in the **Channeldata** folder has started the bot and made it use slash commands. So better than nothing.

**Comment by strongtaste57** [comment]
I'm having the same error. In my case it's a specific server that for some reason triggers the error. I tried on an alt account and as expected, the bot runs fine until I join the server. Tried making a dummy server similar to it, to pinpoint exactly what causes it, but I couldn't find the culprit. Attempted to add an exception in /discum/gateway/start/parse.py for this specific server ID but I couldn't get it to work. I cannot leave this server, so any help would be appreciated.

**Comment by vivinano** [comment]
The developer for discum should be back not sure how long he was going on break but might have to contact him

**Comment by vivinano** [comment]
The dev of discum should be back from hiatus so can some one confirm if this has been resolved

**Comment by tranbtho98** [comment]
Found a way to temporary fix this without deleting any channels, for my case. Discum 1.4.1
Go to your discum package folder: /discum/gateway/types.py. Add some type under channelTypes. For instance:
	channelTypes = {
		0: "guild_text",
		1: "dm",
		2: "guild_voice",
		3: "group_dm",
		4: "guild_category",
		5: "guild_news",
		6: "guild_store",
		10: "guild_news_thread",
		11: "guild_public_thread",
		12: "guild_private_thread",
		13: "guild_stage_voice",
		14: "type_14",
		15: "type_15"
	}
It seems like discord add some kind of honeypot type of channel? The guild parsing got index out of bound due to the extra number of type. The code below was replaced under #take_care_of_channels for debugging.
`				if isinstance(guild["channels"], list):
					for n in guild["channels"]:
						try:
							ready_data["guilds"][guild["id"]]["channels"] = {n["id"]:dict(n,**{"type":Types.channelTypes[n["type"]]})}
						except Exception as e:
							print(n["id"])
							print("n: %s \n"%str(n))`
Thanks @MujurID for the lead.

**Comment by jodersi** [comment]
Just got this issue and was able to fix it by leaving a server that just started using the new forum feature on discord.

**Comment by vivinano** [comment]
> Found a way to temporary fix this without deleting any channels, for my case. Discum 1.4.1
> 
> Go to your discum package folder: /discum/gateway/types.py. Add some type under channelTypes. For instance:
> 
> 	channelTypes = {
> 
> 		0: "guild_text",
> 
> 		1: "dm",
> 
> 		2: "guild_voice",
> 
> 		3: "group_dm",
> 
> 		4: "guild_category",
> 
> 		5: "guild_news",
> 
> 		6: "guild_store",
> 
> 		10: "guild_news_thread",
> 
> 		11: "guild_public_thread",
> 
> 		12: "guild_private_thread",
> 
> 		13: "guild_stage_voice",
> 
> 		14: "type_14",
> 
> 		15: "type_15"
> 
> 	}
> 
> It seems like discord add some kind of honeypot type of channel? The guild parsing got index out of bound due to the extra number of type. The code below was replaced under #take_care_of_channels only to find what channel causing the error for debugging only.
> 
> ![image](https://user-images.githubusercontent.com/80193357/183785737-1813669c-734b-47a8-8af5-1d07ca972f67.png)
> 
> Thanks @MujurID for the lead.

I think this looks pretty valid as a fix I would love to test it but I haven't ran into the issue myself 

I would recommend anyone having the issue to try this fix as it doesn't seem to be to big of a change to functionality 

@tranbtho98  if you get enough successful results I think you could report your finding to the discum developer and it will help him implement the code in his library

**Comment by ScikuVRC** [comment]
`Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x00000291B334BCD0>>
Traceback (most recent call last):
  File "C:\Users\Sciku\AppData\Roaming\Python\Python310\site-packages\discum\gateway\gateway.py", line 299, in _response_loop
    func(resp)
  File "C:\Users\Sciku\AppData\Local\Programs\Python\Python310\Abysmally\MudaeAutoBot.py", line 748, in on_message
    slashfus = threading.Timer(10.0,waifu_roll,args=[slashchannel,slashget,slashguild])
UnboundLocalError: local variable 'slashget' referenced before assignment`

This just recently started happening, no file change, does anyone know if latest discum broke it or fixes it?

**Comment by vivinano** [comment]
> `Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x00000291B334BCD0>> Traceback (most recent call last): File "C:\Users\Sciku\AppData\Roaming\Python\Python310\site-packages\discum\gateway\gateway.py", line 299, in _response_loop func(resp) File "C:\Users\Sciku\AppData\Local\Programs\Python\Python310\Abysmally\MudaeAutoBot.py", line 748, in on_message slashfus = threading.Timer(10.0,waifu_roll,args=[slashchannel,slashget,slashguild]) UnboundLocalError: local variable 'slashget' referenced before assignment`
> 
> This just recently started happening, no file change, does anyone know if latest discum broke it or fixes it?

this is a different issue not regarding user issue this is an issue with discum which I made a bug fixes in their latest version of their repo. but if it still not working the newer code version of my code has resolved this issue


Plesae do not use this issue to report other issues that are not involving USER issue thank you

**Comment by Fractune** [comment]
So is this keyword error going to be fixed or not? Has it been decided

**Comment by Fractune** [comment]
So is this keyword error going to be fixed or not? Has it been sorted out

**Comment by BellaDona007** [comment]
> Found a way to temporary fix this without deleting any channels, for my case. Discum 1.4.1 Go to your discum package folder: /discum/gateway/types.py. Add some type under channelTypes. For instance: channelTypes = { 0: "guild_text", 1: "dm", 2: "guild_voice", 3: "group_dm", 4: "guild_category", 5: "guild_news", 6: "guild_store", 10: "guild_news_thread", 11: "guild_public_thread", 12: "guild_private_thread", 13: "guild_stage_voice", 14: "type_14", 15: "type_15" } It seems like discord add some kind of honeypot type of channel? The guild parsing got index out of bound due to the extra number of type. The code below was replaced under #take_care_of_channels only to find what channel causing the error for debugging only. ![image](https://user-images.githubusercontent.com/80193357/183785737-1813669c-734b-47a8-8af5-1d07ca972f67.png) Thanks @MujurID for the lead.


Thank you very much, that's the only way to solve it

**Comment by BellaDona007** [comment]
Now this has started to appear
![image](https://user-images.githubusercontent.com/82736191/194430572-f1971c88-a867-42bc-b914-054b1778a4f7.png)

**Comment by XLThinOreos1** [comment]
> Found a way to temporary fix this without deleting any channels, for my case. Discum 1.4.1 Go to your discum package folder: /discum/gateway/types.py. Add some type under channelTypes. For instance: channelTypes = { 0: "guild_text", 1: "dm", 2: "guild_voice", 3: "group_dm", 4: "guild_category", 5: "guild_news", 6: "guild_store", 10: "guild_news_thread", 11: "guild_public_thread", 12: "guild_private_thread", 13: "guild_stage_voice", 14: "type_14", 15: "type_15" } It seems like discord add some kind of honeypot type of channel? The guild parsing got index out of bound due to the extra number of type. The code below was replaced under #take_care_of_channels only to find what channel causing the error for debugging only. ![image](https://user-images.githubusercontent.com/80193357/183785737-1813669c-734b-47a8-8af5-1d07ca972f67.png) Thanks @MujurID for the lead.

this does not work for me

**Comment by kleborgn** [comment]
This fork of discum fixed it for me: https://github.com/ericz/Discord-S.C.U.M

**Comment by vivinano** [comment]
> This fork of discum fixed it for me: https://github.com/ericz/Discord-S.C.U.M

Look like the only change I see is a different capability code with self.auth

**Comment by Shirokumowo** [comment]
https://github.com/vivinano/MudaeAutoBot/issues/215#issuecomment-1310162156

**Comment by vivinano** [comment]
Ive pushed a attempted update to try to fix user issue but needs more settings. 
I seen that with a user that has the user error the gateway is still up
