### ISSUE TITLE
problem with discord scum maybe?

### ISSUE THREAD

**Issue by Levkia14** [vivinano/MudaeAutoBot#168]
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x00000226DADBED60>>
Traceback (most recent call last):

**Comment by vivinano** [comment]
could be but this could be very vague as i dont know what the cause was

**Comment by Levkia14** [comment]
i fixed the error now i have this :
Traceback (most recent call last):
  File "C:\Users\sipho\Documents\MudaeAutoBot-4\MudaeAutoBot.py", line 34, in <module>
    bot = discum.Client(token=settings["token"],log={"console":False, "file":False})
  File "C:\Users\sipho\AppData\Roaming\Python\Python310\site-packages\discum\discum.py", line 54, in __init__
    import random_user_agent.user_agent #only really want to import this if needed
ModuleNotFoundError: No module named 'random_user_agent'

**Comment by vivinano** [comment]
When you installed discum you should have gotten all the modules it needed I think you improperly installed it

**Comment by vivinano** [comment]
closing due to expected improper discum installation
