### ISSUE TITLE
File Not Found using Different Method

### ISSUE THREAD

**Issue by Technolord3233** [vivinano/MudaeAutoBot#172]
I've put i my token (I think, I'm getting 2 different tokens, from Network and Local Files. Both don't work, but local files shows nothing happening, Network at least shows soemthing going wrong). I have set up the json file with everything, and checked to make sure it's correct json using a verifier.

`File Not Found using Different Method
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x000002775D4A3810>>
Traceback (most recent call last):
  File "C:\Users\erago\AppData\Roaming\Python\Python310\site-packages\discum\gateway\gateway.py", line 299, in _response_loop
    func(resp)
  File "C:\Users\erago\Documents\!Games\MudaeAutoBot-main\MudaeAutoBot.py", line 748, in on_message
    slashfus = threading.Timer(10.0,waifu_roll,args=[slashchannel,slashget,slashguild])
UnboundLocalError: local variable 'slashget' referenced before assignment
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x000002775D4A3810>>
Traceback (most recent call last):
  File "C:\Users\erago\AppData\Roaming\Python\Python310\site-packages\discum\gateway\gateway.py", line 299, in _response_loop
    func(resp)
  File "C:\Users\erago\Documents\!Games\MudaeAutoBot-main\MudaeAutoBot.py", line 763, in on_message
    msg = get_server_settings(gid,matched_channel)
  File "C:\Users\erago\Documents\!Games\MudaeAutoBot-main\MudaeAutoBot.py", line 180, in get_server_settings
    FsResults = bot.filterSearchResults(FsMsgs)
  File "C:\Users\erago\AppData\Roaming\Python\Python310\site-packages\discum\discum.py", line 313, in filterSearchResults
    return imports.Messages(self.discord, self.s, self.log).filterSearchResults(searchResponse)
  File "C:\Users\erago\AppData\Roaming\Python\Python310\site-packages\discum\messages\messages.py", line 243, in filterSearchResults
    jsonresponse = searchResponse.json()['messages']
KeyError: 'messages'`

**Comment by Technolord3233** [comment]
Also have updated Discum and Python to latest versions

**Comment by vivinano** [comment]
just find a copy of your channel settings and place them in the channeldata folder

**Comment by Technolord3233** [comment]
How do I do this? Just type $settings, and copy paste the message as a txt file? What do I name the file? The ID.txt?

**Comment by vivinano** [comment]
{channelid}.txt be sure to include the bold "*"

**Comment by Technolord3233** [comment]
I did that now, and it was able to read the file. Now im getting some other errors:
Mentions discum so not sure if that is the issue, but it shouldn't as I installed the latest version.
`Reading from File for channel 439215273288007681
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x000001D886BD35B0>>
Traceback (most recent call last):
  File "C:\Users\erago\AppData\Roaming\Python\Python310\site-packages\discum\gateway\gateway.py", line 299, in _response_loop
    func(resp)
  File "C:\Users\erago\Documents\!Games\MudaeAutoBot-main\MudaeAutoBot.py", line 764, in on_message
    c_settings = parse_settings_message(msg)
  File "C:\Users\erago\Documents\!Games\MudaeAutoBot-main\MudaeAutoBot.py", line 226, in parse_settings_message
    settings['prefix'] = val_parse(settings_p[0])[0]
IndexError: list index out of range
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x000001D886BD35B0>>
Traceback (most recent call last):
  File "C:\Users\erago\AppData\Roaming\Python\Python310\site-packages\discum\gateway\gateway.py", line 299, in _response_loop
    func(resp)
  File "C:\Users\erago\Documents\!Games\MudaeAutoBot-main\MudaeAutoBot.py", line 748, in on_message
    slashfus = threading.Timer(10.0,waifu_roll,args=[slashchannel,slashget,slashguild])
UnboundLocalError: local variable 'slashget' referenced before assignment`

**Comment by Technolord3233** [comment]
also just checking, is this what is meant to be inside the txt file:
`· Prefix: $ ($prefix)
· Lang: en ($lang)
· Claim reset: every 180 min. ($setclaim)
· Exact minute of the reset: xx:48 ($setinterval)
· Reset shifted: by +0 min. ($shifthour)
· Rolls per hour: 8 ($setrolls)
· Time before the claim reaction expires: 45 sec. ($settimer)
· Spawn rarity multiplicator for already claimed characters: 1 ($setrare)
· Server game mode: 2 ($gamemode)
· $servlimroul = 27054 $wa, 26872 $ha, 18081 $wg, 15112 $hg
· This channel instance: 1 ($channelinstance)
· Slash commands: enabled ($toggleslash)

· Ranking: enabled ($toggleclaimrank/$togglelikerank)
· Ranks displayed during rolls: disabled ($togglerolls)
· Hentai series: disabled ($togglehentai)
· Disturbing imagery series: disabled ($toggledisturbing)
· Rolls sniping: 0 ($togglesnipe)
· Kakera sniping: 0 ($togglekakerasnipe)
· Limit of characters per harem: 8100 ($haremlimit)
· Reacts: for public wishes only ($togglereact)
· Custom reactions: yes ($claimreact list)

· Kakera trading: enabled ($togglekakeratrade)
· Kakera calculation: claims and likes ranks (and number of claimed characters) ($togglekakeraclaim/$togglekakeralike)
· Kakera value displayed during rolls: enabled ($togglekakerarolls)
· $kakeraloot wishprotect: enabled ($togglewishprotect)`

**Comment by vivinano** [comment]
You forgot the bold *'s

**Comment by Technolord3233** [comment]
Oh i didnt realise when you copy paste from discord it removes the bold *'s. I put all the *'s in, but Im still getting the same error as before
[439215273288007681.txt](https://github.com/vivinano/MudaeAutoBot/files/8841572/439215273288007681.txt)

**Comment by Technolord3233** [comment]
It looks like it is working now, hasn't found anyone to claim yet though so can't see if that works. 
Also what needs to be commented out for this? 
use_emoji - This setting only works if you change the Mudaebot.py code by uncommenting out the line (Custom emojis only) e.g. "<:emoji_name:795############214>"

**Comment by Technolord3233** [comment]
I'm now getting another strange error. Bot was working fine, but now it doesn't work one one of my accounts. If I change the token to an alt, it works, but the original token for the original account isn't working. I tried copying the token again from discord and it doesn't fix it.
`Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x0000021FAC7536E0>>
Traceback (most recent call last):
  File "C:\Users\erago\AppData\Roaming\Python\Python310\site-packages\discum\gateway\gateway.py", line 299, in _response_loop
    func(resp)
  File "C:\Users\erago\Documents\!Games\MudaeAutoBot-main\MudaeAutoBot.py", line 755, in on_message
    user = bot.gateway.session.user
  File "C:\Users\erago\AppData\Roaming\Python\Python310\site-packages\discum\gateway\session.py", line 42, in user
    return self.settings_ready['user']
KeyError: 'user'`

**Comment by vivinano** [comment]
Duplicate issue refer to the one that is still open and ongoing
