### ISSUE TITLE
New error related to discum?

### ISSUE THREAD

**Issue by xd-mau5** [vivinano/MudaeAutoBot#175]
```
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0xffff877202a0>>
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/discum/gateway/gateway.py", line 299, in _response_loop
    func(resp)
  File "./bot.py", line 755, in on_message
    user = bot.gateway.session.user
  File "/root/.local/lib/python3.8/site-packages/discum/gateway/session.py", line 42, in user
    return self.settings_ready['user']
KeyError: 'user'
```

**Comment by vivinano** [comment]
Same issue that has not been resolved yet please keep it in one thread
