### ISSUE TITLE
binascii.Error: Incorrect padding

### ISSUE THREAD

**Issue by Idiot1183** [vivinano/MudaeAutoBot#195]
C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe C:/Users/user/OneDrive/Desktop/random/Norton/norton.py
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\importmanager.py", line 10, in func
    return globals()[name](*args, **kwargs)
KeyError: 'Login'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\OneDrive\Desktop\random\Norton\norton.py", line 37, in <module>
    bot = discum.Client(token=settings["token"], log={"console": False, "file": False})
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\discum.py", line 104, in __init__
    self.__xfingerprint = self.getXFingerprint(generateIfNone=True)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\discum.py", line 216, in getXFingerprint
    return imports.Login(self.s, self.discord, self.log).getXFingerprint(generateIfNone)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\importmanager.py", line 13, in func
    return globals()[name](*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\start\login.py", line 26, in __init__
    self.userID = base64.b64decode(token.split('.')[0]).decode('utf-8')
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

Process finished with exit code 1

I think the issue lies in the user token for this account

**Comment by vivinano** [comment]
? Did you enter your user token ?

**Comment by Idiot1183** [comment]
> ? Did you enter your user token ?

Yes

**Comment by Idiot1183** [comment]
If fixed it by changing
`		if '.' in token:
			self.userID = base64.b64decode(token.split('.')[0]).decode('utf-8')
`
in discum\start\login.py
to

`		if '.' in token:
			userId = token.split('.')[0] + '=' * (-len(token.split('.')[0]) % 4)
			self.userID = base64.b64decode(userId).decode('utf-8')
		#   self.userID = base64.b64decode(token.split('.')[0]).decode('utf-8')
`

**Comment by Idiot1183** [comment]
![image](https://user-images.githubusercontent.com/82732420/184508061-844714f9-57ed-4ef5-93fa-8903e9f6fa45.png)

to

![image](https://user-images.githubusercontent.com/82732420/184508080-98db110b-d073-44ce-b463-49a97c2dcf33.png)
