### ISSUE TITLE
How do I fix this?

### ISSUE THREAD

**Issue by Damilio12** [vivinano/MudaeAutoBot#211]
A friend has been trying to help me with this problem, but we couldn't, so he suggested asking for help here.

So if anyone knows why this happens I would appreciate it if you can give me the solution or the reason why this happens, problem:

```Traceback (most recent call last):
  File "C:\Users\Klever\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\Klever\AppData\Local\Programs\Python\Python310\lib\json__init.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Klever\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Klever\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Klever\AppData\Local\Programs\Python\Python310\Scripts\MudaeAutoBot-main\MudaeAutoBot.py", line 35, in <module>
    bot = discum.Client(token=settings["token"],log={"console":False, "file":False})
  File "C:\Users\Klever\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\discum.py", line 104, in init
    self.xfingerprint = self.getXFingerprint(generateIfNone=True)
  File "C:\Users\Klever\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\discum.py", line 216, in getXFingerprint
    return imports.Login(self.s, self.discord, self.log).getXFingerprint(generateIfNone)
  File "C:\Users\Klever\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\start\login.py", line 38, in getXFingerprint
    xfingerprint = reqxfinger.json().get('fingerprint')
  File "C:\Users\Klever\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by vivinano** [comment]
no token present it seems
