### ISSUE TITLE
Will not start, saying this in idle

### ISSUE THREAD

**Issue by Sogakingdom** [vivinano/MudaeAutoBot#225]
= RESTART: C:\Users\me\Downloads\MudaeAutoBot-main\MudaeAutoBot-main\MudaeAutoBot.py
Traceback (most recent call last):
  File "C:\Users\me\Downloads\MudaeAutoBot-main\MudaeAutoBot-main\MudaeAutoBot.py", line 32, in <module>
    settings = json.load(jsonf)
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 24 column 7 (char 485)

**Comment by vivinano** [comment]
Invalid json setting I think it look like your missing a CommaSent from my iPhoneOn Jan 15, 2023, at 3:22 AM, Sogakingdom ***@***.***> wrote:﻿
= RESTART: C:\Users\me\Downloads\MudaeAutoBot-main\MudaeAutoBot-main\MudaeAutoBot.py
Traceback (most recent call last):
File "C:\Users\me\Downloads\MudaeAutoBot-main\MudaeAutoBot-main\MudaeAutoBot.py", line 32, in 
settings = json.load(jsonf)
File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\json_init_.py", line 293, in load
return loads(fp.read(),
File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\json_init_.py", line 346, in loads
return _default_decoder.decode(s)
File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 353, in raw_decode
obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 24 column 7 (char 485)

**Comment by Sogakingdom** [comment]
i tried writing a comma line 24 column 7 and it told me invalid syntax for where the comma was

**Comment by Sogakingdom** [comment]
![image](https://user-images.githubusercontent.com/122720195/212553244-6aa999f5-e9a9-4aaf-b30a-3393becc1e59.png)
line 24 column 7 is between "def" and "_check_size_limit"

**Comment by Sogakingdom** [comment]
nevemind you said in the json settings, i found it
thanks
