### ISSUE TITLE
Requesting Assistance:

### ISSUE THREAD

**Issue by Alexander-Gremory** [vivinano/MudaeAutoBot#250]
Could you add me on discord or assist me? I know you are fed up with python basic issues, so I am willing to use cashapp or something for a donation? I don't understand python.

```
Reading from File for channel [removed]
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x00000147477BE180>>
Traceback (most recent call last):
  File "C:\Users\ericg\AppData\Roaming\Python\Python311\site-packages\discum\gateway\gateway.py", line 299, in _response_loop
    func(resp)
  File "C:\Users\ericg\Downloads\MudaeAutoBot-4\MudaeAutoBot.py", line 694, in on_message
    c_settings = parse_settings_message(msg)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ericg\Downloads\MudaeAutoBot-4\MudaeAutoBot.py", line 234, in parse_settings_message
    settings['claim_snipe'][0] = int(settings['claim_snipe'][0])
                                     ~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

Ran in Idle:
```
Traceback (most recent call last):
  File "C:\Users\ericg\Downloads\MudaeAutoBot-4\MudaeAutoBot.py", line 2, in <module>
    import discum
ModuleNotFoundError: No module named 'discum'
>>> 
```

**Comment by Alexander-Gremory** [comment]
I've installed discum, but it isn't working and I've tried referencing old issue forms here. I don't understand what I am doing at all though. How much money to get direct assistance teamviewer or discord?

**Comment by Alexander-Gremory** [comment]
Ive completely uninstalled and reinstalled python just to try anything...

IDLE:
```
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x00000276E9516E90>>
Traceback (most recent call last):
  File "C:\Users\ericg\AppData\Roaming\Python\Python311\site-packages\discum\gateway\gateway.py", line 299, in _response_loop
    func(resp)
  File "C:\Users\ericg\Downloads\MudaeAutoBot-4\MudaeAutoBot.py", line 694, in on_message
    c_settings = parse_settings_message(msg)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ericg\Downloads\MudaeAutoBot-4\MudaeAutoBot.py", line 234, in parse_settings_message
    settings['claim_snipe'][0] = int(settings['claim_snipe'][0])
                                     ~~~~~~~~~~~~~~~~~~~~~~~^^^

IndexError: list index out of range```

Terminal:
```Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x00000276E9516E90>>
Traceback (most recent call last):
  File "C:\Users\ericg\AppData\Roaming\Python\Python311\site-packages\discum\gateway\gateway.py", line 299, in _response_loop
    func(resp)
  File "C:\Users\ericg\Downloads\MudaeAutoBot-4\MudaeAutoBot.py", line 694, in on_message
    c_settings = parse_settings_message(msg)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ericg\Downloads\MudaeAutoBot-4\MudaeAutoBot.py", line 234, in parse_settings_message
    settings['claim_snipe'][0] = int(settings['claim_snipe'][0])
                                     ~~~~~~~~~~~~~~~~~~~~~~~^^^```

**Comment by Alexander-Gremory** [comment]
I've tried everything I could find and can't solve this gateway error, I don't know what to do man

**Comment by vivinano** [comment]
Seems like your aren’t having a setting instance in your channel so this might be token related Sent from my iPhoneOn Jul 20, 2023, at 12:52 PM, Alexander-Gremory ***@***.***> wrote:﻿
I've tried everything I could find and can't solve this gateway error, I don't know what to do man

**Comment by Alexander-Gremory** [comment]
![image](https://github.com/vivinano/MudaeAutoBot/assets/16449038/51d729b6-8706-46b2-890c-bec81f0df858)
![image](https://github.com/vivinano/MudaeAutoBot/assets/16449038/efcc41ea-5951-4a87-86e6-67feda906fba)
![image](https://github.com/vivinano/MudaeAutoBot/assets/16449038/02f10793-feb5-47fc-8047-e191b92a88b4)

I ran $setting in the channel as well.

The only thing I've managed to fix is the not finding discum module. I don't know what to fix or where my problem is now. Token is in settings and is working. Please tell me what to do. Or please help me with teamviewer or discord screen share. I have cashapp and paypal.

**Comment by Alexander-Gremory** [comment]
![image](https://github.com/vivinano/MudaeAutoBot/assets/16449038/6056e25a-76aa-4911-8e17-4d95c10595a3)
Not sure what caused this change, but this popped up one time while running it

**Comment by ZIPendr** [comment]
I got the exact same problem,
`Reading from File for channel 695382294046965760
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x0000018A886DC630>>
Traceback (most recent call last):
  File "C:\Users\oscar\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\gateway\gateway.py", line 299, in _response_loop
    func(resp)
  File "C:\Users\oscar\Desktop\MudaeAutoBot-4\MudaeAutoBot.py", line 694, in on_message
    c_settings = parse_settings_message(msg)
  File "C:\Users\oscar\Desktop\MudaeAutoBot-4\MudaeAutoBot.py", line 234, in parse_settings_message
    settings['claim_snipe'][0] = int(settings['claim_snipe'][0])
IndexError: list index out of range`

from IDLE:
`Reading from File for channel 695382294046965760
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x000001E1048469D0>>
Traceback (most recent call last):
  File "C:\Users\oscar\AppData\Local\Programs\Python\Python310\lib\site-packages\discum\gateway\gateway.py", line 299, in _response_loop
    func(resp)
  File "C:\Users\oscar\Desktop\MudaeAutoBot-4\MudaeAutoBot.py", line 694, in on_message
    c_settings = parse_settings_message(msg)
  File "C:\Users\oscar\Desktop\MudaeAutoBot-4\MudaeAutoBot.py", line 234, in parse_settings_message
    settings['claim_snipe'][0] = int(settings['claim_snipe'][0])
IndexError: list index out of range`

I just fixed the problem {user} from discum (fixed by creating an alt and only having 1 server lol) 
but now i got this error too

**Comment by vivinano** [comment]
there some fixes with manaul setting of guilds as somehow its unable to grab the guild id if you have alot of guilds maybe its a limitation of the variable its stored in i might have to check on that

**Comment by BeruJazu** [comment]
any updates on these one
