### ISSUE TITLE
UnboundLocalError: local variable 'settings_hope_prefix' referenced before assignment

### ISSUE THREAD

**Issue by larrryfisherthefisherman** [vivinano/MudaeAutoBot#277]
File Not Found using Different Method
Default $settings used for channel 13323474257155487980
Exception ignored in thread started by: <bound method GatewayServer._response_loop of <discum.gateway.gateway.GatewayServer object at 0x0000020211B776E0>>
Traceback (most recent call last):
  File "C:\Users\Steven\AppData\Roaming\Python\Python310\site-packages\discum\gateway\gateway.py", line 299, in _response_loop
    func(resp)
  File "C:\Users\Steven\Desktop\MudaeAutoBot-4\MudaeAutoBot.py", line 693, in on_message
    msg = get_server_settings(gid,matched_channel)
  File "C:\Users\Steven\Desktop\MudaeAutoBot-4\MudaeAutoBot.py", line 186, in get_server_settings
    · Prefix: **{settings_hope_prefix}** ($prefix)
UnboundLocalError: local variable 'settings_hope_prefix' referenced before assignment

**Comment by nasseralharbi12** [comment]
did you solve it ? I have the same  Issue
