### ISSUE TITLE
The Cmd Prompt instantly close when i run the file

### ISSUE THREAD

**Issue by w1bu2** [vivinano/MudaeAutoBot#57]
When i run MudaeAutoBot.py it just open the cmd prompt then instaly close it

**Comment by vivinano** [comment]
havent recieved respone assuming issue has been self-resolved

**Comment by NL1693** [comment]
Ran it in IDLE and this is what it shows

>>> 
= RESTART: C:\Users\amanm\Desktop\Automation\Bots\MudaeAutoBot-main\MudaeAutoBot-main\MudaeAutoBot.py
Traceback (most recent call last):
  File "C:\Users\amanm\Desktop\Automation\Bots\MudaeAutoBot-main\MudaeAutoBot-main\MudaeAutoBot.py", line 29, in <module>
    settings = json.load(jsonf)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 5 column 4 (char 150)
>>>

**Comment by vivinano** [comment]
Show setting_.json I think you have a trailing comma somewhere 

Plz black out user token b4 posting thanks you
